using HotelBooking.infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Testcontainers.MsSql;

// Using TestHotelBookingDBContext instead of HotelBookingDBContext
// to avoid conflicts with hardcoded OnConfiguring in DB-First scaffolded files.
namespace HotelBooking.Tests.Integration;

/// <summary>
/// Base class for Integration Testing.
/// Automatically spins up a SQL Server container using Docker, creates the database, and seeds initial data.
/// Each Test Class inheriting from this will have its own isolated SQL Server container.
/// 
/// DIFFERENCE FROM UNIT TESTS:
/// - Unit Test: Mocks everything (Repository, UnitOfWork) -> tests business logic only.
/// - Integration Test: Uses a real DB -> tests logic + data layer + Foreign Key constraints.
/// </summary>
public abstract class IntegrationTestBase : IAsyncLifetime
{
    // ===== DOCKER CONTAINER =====
    // Testcontainers will automatically pull the SQL Server image and create the container
    private readonly MsSqlContainer _dbContainer = new MsSqlBuilder()
        .WithImage("mcr.microsoft.com/mssql/server:2022-latest") // SQL Server Image
        .Build();

    protected IConfiguration _configuration = null!;
    protected HotelBookingDBContext _dbContext = null!;
    protected UnitOfWork _unitOfWork = null!;
    protected IServiceProvider _serviceProvider = null!;

    // Abstract -> Forces each test class to declare its own dependencies
    protected abstract IServiceProvider BuildServiceProvider(
        HotelBookingDBContext dbContext,
        IConfiguration config);

    /// <summary>
    /// xUnit calls this method BEFORE running any tests.
    /// Execution Flow: Start Docker -> Create DbContext -> Create Tables -> Seed Data.
    /// </summary>
    public async Task InitializeAsync()
    {
        // 1. Load configuration from appsettings.test.json (JWT key, Issuer, Audience...)
        _configuration = new ConfigurationBuilder()
            .SetBasePath(AppContext.BaseDirectory)
            .AddJsonFile("appsettings.test.json")
            .Build();

        // 2. Start SQL Server container (Docker pulls image automatically if missing)
        await _dbContainer.StartAsync();

        // 3. Initialize DbContext connecting to the container
        //   - Use TestHotelBookingDBContext (derived class) instead of HotelBookingDBContext
        //   - Avoid conflict with hardcoded OnConfiguring() in scaffolded files.
        var options = new DbContextOptionsBuilder<HotelBookingDBContext>()
            .UseSqlServer(_dbContainer.GetConnectionString()) // Connection string generated by Testcontainers
            .Options;

        _dbContext = new TestHotelBookingDBContext(options);

        // 4. Create all tables based on OnModelCreating (similar to migrations)
        await _dbContext.Database.EnsureCreatedAsync();

        // 5. Seed essential data (Roles are mandatory)
        await SeedRolesAsync();

        // 6. Initialize real UnitOfWork (No mocking!)
        _unitOfWork = new UnitOfWork(_dbContext);

        // Invoke abstract method once DB is ready
        _serviceProvider = BuildServiceProvider(_dbContext, _configuration);
    }

    /// <summary>
    /// Seed 3 basic Roles into the DB.
    /// Required because RegisterCustomer/RegisterAdmin need a RoleId assignment.
    /// 
    /// DB-FIRST CHALLENGE: The Id column is an IDENTITY (auto-increment). 
    /// Standard EF Core cannot insert explicit values.
    /// SOLUTION: Use raw SQL with SET IDENTITY_INSERT ON to force specific IDs.
    /// </summary>
    private async Task SeedRolesAsync()
    {
        if (!await _dbContext.Roles.AnyAsync())
        {
            // Use raw SQL because EF Core restricts explicit values in identity columns
            await _dbContext.Database.ExecuteSqlRawAsync(@"
                SET IDENTITY_INSERT Roles ON;
                INSERT INTO Roles (Id, Name, IsDeleted) VALUES (1, 'Admin', 0);
                INSERT INTO Roles (Id, Name, IsDeleted) VALUES (2, 'Customer', 0);
                INSERT INTO Roles (Id, Name, IsDeleted) VALUES (3, 'Owner', 0);
                SET IDENTITY_INSERT Roles OFF;
            ");
        }
    }

    /// <summary>
    /// Helper: Cleans up data after each test (Roles are preserved).
    /// Call this at the start of each test method to ensure isolation.
    /// </summary>
    protected async Task CleanupDataAsync()
    {
        // Delete order: Child tables first, then Parent tables (to respect FK constraints)
        _dbContext.UserRoles.RemoveRange(_dbContext.UserRoles);
        _dbContext.Users.RemoveRange(_dbContext.Users);
        await _dbContext.SaveChangesAsync();
    }

    /// <summary>
    /// xUnit calls this method AFTER all tests have finished.
    /// Cleanup: Dispose DbContext -> Stop Docker container.
    /// </summary>
    public async Task DisposeAsync()
    {
        await _dbContext.DisposeAsync();
        await _dbContainer.StopAsync();
    }
}